image: golang:1.25

stages:
  - test
  - build
  - deploy

unit-tests:
  stage: test
  image: golang:1.25
  script:
    - go test -v ./...
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: never
    - when: on_success

integration-tests:
  stage: test
  image: golang:1.25
  script:
    - go test -v -tags=integration ./...
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: never
    - when: on_success